clusterGroup:
  name: prod
  isHubCluster: true

  namespaces:
    - vault
    - golang-external-secrets
    - rag-llm
    - openshift-nfd
    - nvidia-gpu-operator

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
      channel: stable

    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      channel: v24.6
      source: certified-operators

  projects:
    - rag-llm
    - nfd
    - hub

  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*

    qdrant:
      name: qdrant
      namespace: rag-llm
      project: rag-llm
      path: charts/qdrant
      extraValueFiles:
        - /values-qdrant.yaml

    vllm:
      name: vllm
      namespace: rag-llm
      project: rag-llm
      path: charts/vllm

    rag-llm:
      name: rag-llm
      namespace: rag-llm
      project: rag-llm
      path: charts/rag-llm

    nfd:
      name: nfd
      namespace: openshift-nfd
      project: nfd
      path: charts/nfd
