clusterGroup:
  name: prod
  isHubCluster: true

  namespaces:
    - rag-llm
    - openshift-nfd
    - nvidia-gpu-operator

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
      channel: stable

    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      channel: v24.6
      source: certified-operators

  projects:
    - rag-llm
    - nfd

  applications:
    qdrant:
      name: qdrant
      namespace: rag-llm
      project: rag-llm
      path: charts/qdrant
      extraValueFiles:
        - /values-qdrant.yaml

    vllm-mistral:
      name: vllm-mistral
      namespace: rag-llm
      project: rag-llm
      path: charts/vllm-mistral

    rag-api:
      name: rag-api
      namespace: rag-llm
      project: rag-llm
      path: charts/rag-api

    nfd:
      name: nfd
      namespace: openshift-nfd
      project: nfd
      path: charts/nfd
