apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-api.fullname" . }}
  labels:
    app: {{ include "rag-api.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rag-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rag-api.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{ toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{ toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: QDRANT_URL
              value: http://qdrant:6333
            - name: QDRANT_COLLECTION
              value: rag-collection
            - name: VLLM_URL
              value: http://vllm-mistral-vllm-mistral:8000/v1/completions
