apiVersion: batch/v1
kind: Job
metadata:
  name: load-embeddings
  labels:
    app: {{ include "rag-api.name" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "rag-api.name" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: embeddings-loader
          image: "{{ .Values.loader.image }}:{{ .Values.loader.tag }}"
          imagePullPolicy: {{ .Values.loader.pullPolicy }}
  backoffLimit: 1
