apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-api.fullname" . }}
  labels:
    app: {{ include "rag-api.name" . }}
spec:
  selector:
    app: {{ include "rag-api.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP
