apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-api.fullname" . }}
  labels:
    app: {{ include "rag-api.name" . }}
spec:
  selector:
    app: {{ include "rag-api.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
