api:
  image: quay.io/dminnear/vp-rag-llm-api
  tag: latest
  pullPolicy: Always

  models:
    - name: mistral
      url: http://vllm-vllm:8000
      model_type: vllm
      max_total_tokens: 32768

    - name: gpt-4o
      url: https://api.openai.com/v1/chat/completions
      model_type: openai
      max_total_tokens: 128000

    - name: gpt-4o-mini
      url: https://api.openai.com/v1/chat/completions
      model_type: openai
      max_total_tokens: 128000

  crossEncoderModel: cross-encoder/ms-marco-MiniLM-L-6-v2

qdrant:
  url: http://qdrant:6333
  collection: rag-collection

loader:
  image: quay.io/dminnear/vector-embedder
  tag: latest
  pullPolicy: Always

  dbType: qdrant

  repoSources:
    - repo: https://github.com/validatedpatterns/docs
      globs:
        - "content/blog/**/*"
        - "content/contribute/**/*"
        - "content/learn/**/*"
        - "content/patterns/**/*"

  webSources:
    - https://www.intel.com/content/www/us/en/content-details/819918/red-hat-openshift-data-science-workflows-with-red-hat-validated-patterns-5th-gen-intel-xeon-solutions-reference-architecture.html
    - https://www.redhat.com/en/topics/cloud-computing/what-are-validated-patterns
    - https://www.redhat.com/en/products/edge/validated-patterns
    - https://cdrdv2-public.intel.com/819918/PUBLIC-accelerate-work-with-red-hat-validated-patterns-ref-arch0408.pdf
    - https://www.spiceworks.com/tech/edge-computing/guest-article/how-to-build-validated-patterns-for-continuous-ai-deployment-at-the-edge/

chunking:
  size: 2048
  overlap: 50

ui:
  image: quay.io/dminnear/vp-rag-llm-ui
  tag: latest
  pullPolicy: Always

secretStore:
  name: vault-backend
  kind: ClusterSecretStore
  remoteKey: secret/data/global/openai

embedder:
  model: BAAI/bge-large-en-v1.5
