apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    app: {{ include "vllm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vllm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "vllm.name" . }}
    spec:
      containers:
        - name: vllm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--model"
            - {{ .Values.model.name | quote }}
            - "--dtype"
            - {{ .Values.model.dtype | quote }}
            - "--served-model-name"
            - {{ .Values.model.servedName | quote }}
            - "--tokenizer-mode"
            - {{ .Values.model.tokenizerMode | quote }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-cache
              mountPath: {{ .Values.persistence.mountPath }}
          env:
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "1"
            - name: HF_HOME
              value: {{ .Values.persistence.mountPath }}
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: {{ include "vllm.fullname" . }}-model-cache
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: gpu
