apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hf-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: hf-secret
    template:
      type: Opaque
  data:
    - secretKey: hf_token
      remoteRef:
        key: {{ .Values.secretStore.remoteKey }}
        property: hftoken
