apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm.fullname" . }}
spec:
  selector:
    app: {{ include "vllm.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
